name: Build Eden Nightly
concurrency:
  group: build-eden-nightly-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

jobs:
  android: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [Optimised]
    continue-on-error: true
    name: "Android (${{ matrix.target }})"
    env:
      TARGET: ${{ matrix.target }}    
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install glslang-tools libvulkan-dev -y
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Install NDK 27 (explicitly)
        uses: android-actions/setup-android@v2
        with:
          ndk-version: "27.0.11718014"  # Must match exact version

      - name: Block Yuzu from installing NDK 26
        run: |
          mkdir -p "$HOME/.android"
          echo "ndk.dir=$ANDROID_HOME/ndk/27.0.11718014" > "$HOME/.android/local.properties"
          echo "sdk.dir=$ANDROID_HOME" >> "$HOME/.android/local.properties"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.0.11718014" >> $GITHUB_ENV

      - name: Verify NDK version
        run: |
          $ANDROID_NDK_HOME/ndk-build --version
        
      - name: Compile Eden android
        run: |
          chmod +x ./eden-android.sh
          ./eden-android.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-android-${{ matrix.target }}
          path: eden/src/android/artifacts/
